### ISSUE TITLE
crashDump 目录下没有崩溃日志文件

### ISSUE THREAD

**Issue by eateeer** [AndroidAdvanceWithGeektime/Chapter01#1]
根据 README.md 里面的方法，成功运行了项目，然后授予存储权限、点击按钮项目崩溃，在 `/sdcard/crashDump/` 目录下没有任何文件：

```
~/Documents/AndroidAdvanceWithGeektime/Chapter01 master*
❯ adb pull /sdcard/crashDump/ ~/Desktop
/sdcard/crashDump/: 0 files pulled.
``` 

无论是在真机测试（Android 7.1）还是用模拟器 (Android 9.0 和 Android 5.1) 测试都出现了这样的情况。
请问是还需要作其他操作么？

**Comment by dodola** [comment]
@wl9739 请问一下是x86的模拟器么？

**Comment by eateeer** [comment]
@dodola 是 x86 的模拟器。代码里面把 x86 的 ndk 支持注释掉了，我取消了注释，然后在 x86 的模拟器上面跑的。

**Comment by dodola** [comment]
@wl9739 在 x86 模拟器下无法生成日志的解决方法如下：
1. 将 ndk 切换到 16b，下载地址： https://developer.android.com/ndk/downloads/older_releases?hl=zh-cn 
mac 版：https://dl.google.com/android/repository/android-ndk-r16b-darwin-x86_64.zip
2. 在 Androidstudio 里设置 ndk 路径为ndk-16b的路径
3. 在 sample 和 breakpad-build 的 build.gradle 配置里增加如下配置
```
 externalNativeBuild {
            cmake {
                cppFlags "-std=c++11"
                arguments "-DANDROID_TOOLCHAIN=gcc"
            }
        }

```

**Comment by dodola** [comment]
@wl9739 这个问题是因为 clang 的 bug 导致的，在对 linux syscall 的编译支持上 对sys_prctl 这个方法的编译里一个 ebi 指令的偏移出现错误(猜测如此)，后面我会分析一下，现在只能暂时切换到gcc 上进行编译

**Comment by dodola** [comment]
@wl9739 所以例子里去掉了x86 ，不是说不支持哈

**Comment by eateeer** [comment]
@wl9739 谢谢，问题解决了，能导出崩溃日志了！

**Comment by shjborage** [comment]
我这边遇到 Smartisan DE106(Android 8.1.0, API 27) ，在 classDump 里也没找到日志，辛苦帮忙看下。

尝试 x86 的这个方法，但没成功：

```
 externalNativeBuild {
            cmake {
                cppFlags "-std=c++11"
                arguments "-DANDROID_TOOLCHAIN=gcc"
            }
        }
```

这个在 sample 中加了，但在 breakpad-build 中加的时候编译报错，找不到这些定义。

```
Could not find method cppFlags() for arguments [-std=c++11] on object of type
```

只在  sample 里加上再重新试了点 Crash 按钮，但还是没找到崩溃文件。

**Comment by eateeer** [comment]
@shjborage `externalNativeBuild` 的作用域有两个，分别是在 `android{}` 和 `defaultConfig()` 里面。
在 `breakpad-build` 的 gradle 文件中增加的配置其实是在 `defaultConfig{}` 里的，也就是说，`breakpad-build` 模块的完整 gradle 文件代码应该是像下面这样的：
```java
apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86"
        }
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11"
                arguments "-DANDROID_TOOLCHAIN=gcc"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.android.support:appcompat-v7:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```
注意有两个 `externalNativeBuild ` 配置。

**Comment by shjborage** [comment]
多谢指点，我稍后再试下

**Comment by shjborage** [comment]
@wl9739 我按您说的试了下，还是没有生成崩溃信息文件。是否与机型或版本有关？ 我在 `/sdcard/crashDump` 下什么也没发现。点了挺多次 Crash，也尝试删除 APP，重新安装。

```
trident:/sdcard/crashDump $ ls -al
total 16
drwxrwx--x   2 root sdcard_rw  4096 2018-12-03 20:22 .
drwxrwx--x 228 root sdcard_rw 12288 2018-12-04 09:41 ..
```

**Comment by ZJLeBron** [comment]
> @wl9739 谢谢，问题解决了，能导出崩溃日志了！

请问你真机上边怎么搞定的，我真机上边没有日志文件
