### ISSUE TITLE
无法将dmp文件解析成txt

### ISSUE THREAD

**Issue by hansionit** [AndroidAdvanceWithGeektime/Chapter01#17]
自己编译了breakpad,使用编译后的microdump_stackwalk 执行命令， ./tools/mac/microdump_stackwalk test2 > crashLog.txt

报如下错误，网上查不到相关解决方法

`
basic_code_modules.cc:111: INFO: No module at 0x0

stackwalker.cc:270: ERROR: Unknown CPU type 0x0, can't choose a stackwalker implementation

microdump_processor.cc:82: ERROR: No stackwalker found for microdump.

microdump_stackwalk.cc:118: ERROR: MicrodumpProcessor::Process failed (code = 3)
`

**Comment by hansionit** [comment]
两个手机生成的dmp都无法解析

**Comment by hua060097** [comment]
请教下这个最后解了吗
