### ISSUE TITLE
couldn't find "libbreakpad-core.so"

### ISSUE THREAD

**Issue by anakin777** [AndroidAdvanceWithGeektime/Chapter01#3]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dodola.breakpad-jCDdH1ua8M1bzPaGxwn39w==/base.apk"],nativeLibraryDirectories=[/data/app/com.dodola.breakpad-jCDdH1ua8M1bzPaGxwn39w==/lib/arm, /data/app/com.dodola.breakpad-jCDdH1ua8M1bzPaGxwn39w==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libbreakpad-core.so"

**Comment by yuanyang1991** [comment]
需要编译成apk.
android studio  Build --> Build Bundles/Apks  
编译后再安装，然后点击crash 就会有了

**Comment by anakin777** [comment]
> 需要编译成apk.
> android studio Build --> Build Bundles/Apks
> 编译后再安装，然后点击crash 就会有了

可以了谢谢
