### ISSUE TITLE
华为真机8.0 crashDump 无 crash 日志

### ISSUE THREAD

**Issue by hyvenzhu** [AndroidAdvanceWithGeektime/Chapter01#6]
如题

**Comment by xurui1995** [comment]
一加5T 8.1也是

**Comment by dodola** [comment]
@xurui1995 @hiphonezhu 手上没有具体的手机，不知道问题出在哪，可以通过 debug 看一下，到底是register signal catch的时候出的问题，还是注册上了系统没有走到 catch handler 里。也可以尝试不同的平台试一下，比如切换到armeabi-v7a 的

**Comment by xurui1995** [comment]
@dodola 已经解决了，解决方法:  demo生成apk安装，不要Android studio直接run

**Comment by hyvenzhu** [comment]
确认，./gradlew install的可以，./gradlew assemble 的不行
