### ISSUE TITLE
模拟器上运行无dump文件，更换了ndk-16b出现以下错误

### ISSUE THREAD

**Issue by tigerjiang** [AndroidAdvanceWithGeektime/Chapter01#8]
`    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            cppFlags "-std=c++11"
            arguments "-DANDROID_TOOLCHAIN=gcc"
        }
    }` 

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jiangzehu/GeekTime/Chapter01/breakpad-build/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':breakpad-build'.
> Could not find method cppFlags() for arguments [-std=c++11] on object of type com.android.build.gradle.internal.dsl.CmakeOptions.

有人遇到过吗

**Comment by dodola** [comment]
@tigerjiang 你可以看看这个帖子https://github.com/AndroidAdvanceWithGeektime/Chapter01/issues/1

**Comment by dodola** [comment]
还有 https://github.com/AndroidAdvanceWithGeektime/Chapter01/issues/2

**Comment by tigerjiang** [comment]
问题已解决　参考[#1](https://github.com/AndroidAdvanceWithGeektime/Chapter01/issues/1)　配置更改如下
`apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86"
        }
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11"
                arguments "-DANDROID_TOOLCHAIN=gcc"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.android.support:appcompat-v7:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}`
